### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by emmrichd** [lapy/esp32-keyble-homeassistant#1]
Hello,
some hints for installation would be handy, please
Do I need to configure everything in main.cpp or is there a wifi AP/webgui available?

Regards, Dieter

**Comment by lapy** [comment]
Hi @emmrichd ,

unfortunately I abandoned the standard Wireless ESP32 project in favour of an Ethernet based ESP32. A fully wireless project is unfortunately not possible with acceptable responsiveness, while using an Olimex ESP32 Gateway with Ethernet has proven to be rock solid and most importantly super responsive (commands from Home Assistant are executed instantly all the time!). I will be pushing the code shortly into this repo with some info about how to configure and what hardware it has been tested on.

Regards, Vince

**Comment by peterrn2** [comment]
Hi Vince,
reading your project I thought I was in wonderland.
Beeing able to use the Equiva Lock simply after compiling and flashing sounds marvelous.
I read about the difficulties to simultaneously use WIFI and Bluetooth on a ESP32 so using a ESP32 Gateway makes sense.

My question: do you plan to support differenz boards like the WT32-ETH0?
This has a smaller board and can be bougth from Amazon at lower shipping costs.
Thanks for your reply.
Peter.

**Comment by lapy** [comment]
Hi Peter,
I am not able to support different boards simply because I do not own other boards. But you can try to adapt the project to your board, maybe it even works without changes :)
