### ISSUE TITLE
Q: Does BT always on Feature block Smartphone Access?

### ISSUE THREAD

**Issue by stevenengland** [lapy/esp32-keyble-homeassistant#3]
Hi Lapy,

I am very excited reading the details of this ESP32 port. Before I buy the hardware I would like to know if there are any issues in conjunction with the smartphone apps. Does BT always on mean that the ESP is always connected? If so it should not be possible to control the lock via smartphone in the meantime. Is that correct?

Kind regards

**Comment by lapy** [comment]
Hi Stephen,
yes, the esp32 will always be connected so the app will not work any more until you power down the gateway.

**Comment by stevenengland** [comment]
Hi Lapy, 

thank you for the details. Unfortunately that means a showstopper at the moment.

Nevertheless - great work!

**Comment by lapy** [comment]
Sorry it doesn’t work for you, it’s a trade off due to the BT platform limitations. In my case I have a production HomeAssistant that I use as my main house automation server, so I would not the use the lock app anyway.
Reliability so far has been very good!
Thanks for checking this fork anyway :)
